
variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

stages:
  - lint
  - build

lint:
  stage: lint
  image: rust:latest
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
  cache:
    paths:
      - cargo
      - target

rust-latest:
  stage: build
  image: rust:latest
  script:
    - rustup target add thumbv7em-none-eabihf
    - cargo build --verbose
  cache:
    paths:
      - cargo
      - target

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  allow_failure: true
  script:
    - rustup target add thumbv7em-none-eabihf
    - cargo build --verbose
  cache:
    key: nightly-cache
    paths:
      - cargo
      - target
