stages:
  - lint
  - build

lint:
  stage: lint
  image: rust:latest
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check

rust-latest:
  stage: build
  image: rust:latest
  script:
    - rustup target add thumbv7em-none-eabihf
    - cargo build --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - rustup target add thumbv7em-none-eabihf
    - cargo build --verbose
  allow_failure: true
